name: push

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: JS-DevTools/npm-publish@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.NPM_AUTH_TOKEN }}
